TP-8723: Extend Danger to warn against missing translation
moneyadviceservice/mas-standards pull request #8
Opened 2019-01-04 17:06 UTC by scruti

[TP-8723](https://moneyadviceservice.tpondemand.com/entity/8723-create-language-yaml-file-comparator-script)

A common and painful mistake is to modify/extend the English locale
translations while forgetting to do the same for Welsh.
Then this is discovered during testing or even worse, already in
Staging/Production, and for a really tiny code change, the developer
needs to go again through all the release process, losing hours of
work.

This change adds a new check into Danger, allowing the tool to warn us
in the Pull Request when, having both Welsh and English locale files
present, we only pushed changes into one of the languages.

In this way we aim to detect missing translations as soon as possible.

## Tested cases
Using PACS ad-hoc PR against local running version of Dangerfile.

### Welsh and English locales, but only English contains changes
**Result: Warning**
![screenshot from 2019-01-04 16-44-37](https://user-images.githubusercontent.com/1227578/50700389-574c1280-1042-11e9-9698-7b5db13a3268.png)

### Welsh and English locales, but only Welsh contains changes
**Result: Warning**
![screenshot from 2019-01-04 16-50-13](https://user-images.githubusercontent.com/1227578/50700542-b27e0500-1042-11e9-9ffa-5222e3e914c8.png)

### Welsh and English locales, but the changes are in codebase without touching locales
**Result: No warning**
![screenshot from 2019-01-04 16-46-48](https://user-images.githubusercontent.com/1227578/50700471-8bbfce80-1042-11e9-8185-4268d402e957.png)

### Welsh and English locales, changes on both locales
**Result: No warning**
![screenshot from 2019-01-04 16-48-53](https://user-images.githubusercontent.com/1227578/50700510-9f6b3500-1042-11e9-826a-b22df6e1515f.png)

### Only English locale is present in the project, and has some changes
**Result: No warning**
![screenshot from 2019-01-04 16-52-32](https://user-images.githubusercontent.com/1227578/50700575-cb86b600-1042-11e9-93b2-a01656407925.png)
.

2019-01-07 10:10 UTC, margOnline requested changes
This is a great first step to addressing the issue where Welsh changes are not included, often because they are not included on the TP card. 

My concern is that if we implement this change, we become reliant on the danger warning. This solution will not address the issue where both files have been changed but the keys are not the same e.g. a key has been missed off. Should we create another card to address the solution more completely? Am I overthinking it? 

I'm requesting changes not as a blocker but to generate discussion.

2019-01-07 10:22 UTC, scruti commented
Was checking to implement the keys difference check in the `git push` rubocop/tests script, but now that you raised it I am going to investigate if can be implemented in Danger itself together with this check.

Good call! 

Moving this PR into WIP meanwhile.

2019-01-07 15:08 UTC, scruti commented
@margOnline pushed a new commit checking for key disparities between both locales.

I'm pushing a little bit the limits of Danger here as I had to:
- Define a method.
- Make the conditionals more complex.

Due to that I didn't even want to jump into things like:
- Showing the full path of the missing keys: Found how to on Google but would make code way more complex.
- Check only keys that have been modified by the branch: Can be done with regex and Danger git module, but:
  - Again, would make the code way more complex.
  - Probably we want to be warned about differences even if they weren't introduced in the PR itself. For example in PACS I already found some pending differences thank to this:
![screenshot from 2019-01-07 14-44-25](https://user-images.githubusercontent.com/1227578/50775394-f57fe880-128d-11e9-9136-e9dcbd1cd0c1.png)
The tooltip_show/hide weren't part of my testing changes, and they differ on master. 

Let me know what do you think :)

2019-01-08 14:26 UTC, margOnline approved these changes
nice work!

2019-01-08 14:26 UTC, margOnline commented on Dangerfile
> +      keys.push(key, *get_all_keys(val))
nice use of recursion

2019-01-09 16:07 UTC, tomas-stefano approved these changes
👏 👏 👏 ❤️ 🕺

2019-01-09 16:18 UTC, scruti commented
:shipit:

2019-01-09 16:19 UTC, merged